### PR TITLE
create views:  VideContent ,VideosOfCategory. and fix some design

### PR DESCRIPTION
**Pull request by Ziayoub**

### CODE REVIEW

**Comment by zianwar** [comment]
- Fix styling of all videos to be exactly like in categories.

Screen Shot 2020-01-22 at 12 33 50 PM
Screen Shot 2020-01-22 at 12 33 38 PM

**Comment by zianwar** [comment]
- Show Icons and colors for category cards:

Screen Shot 2020-01-22 at 12 38 04 PM

**Comment by zianwar** [comment]
- Fix this
Screen Shot 2020-01-22 at 12 39 10 PM

**Comment by zianwar** [comment]
Fix those UI issues above, then we can have another meeting.

**Comment by Ziayoub** [comment]
Some categories they don't have icons that why i removed them.

**Comment by zianwar** [comment]
You can add any icon for now just to see how they look

**Comment by zianwar** [comment]
Looks good now 👍

**Pull request merged**
